# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 710f558c093bc77a97f4d5bc2c6c2282936f4b1f9088f2dc7b25022fb85d27f5bbfff04cc286b30bfa98f530eb4952330d306e0793994e2a1714b0c6150f7563

test:
  secret_key_base: 4b8d973837c57f8eaeb986729973f487457c5e5d2f357ab9d79b86fef9124358c29d0d0ed7388cca24110aa00e6c06b751f602acb982093749ee78507e77ff0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
